backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "landing"
    label: "Landing Page"
    file: "src/pages/landing/index.md"
    files:
      - file: "src/pages/landing/topsection.md"
        label: "Top Section"
        name: "topsection"
        fields:
          - {
              label: Main Image,
              name: mainimage,
              widget: object,
              fields:
                [
                  {
                    label: Background Image,
                    name: background-image,
                    widget: image,
                  },
                  { label: Mini Image 1, name: mini-image-1, widget: image },
                  { label: Mini Image 2, name: mini-image-2, widget: image },
                ],
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Description, name: description, widget: text }

      - file: "src/pages/landing/section1.md"
        label: "Section 1"
        name: "section1"
        fields:
          [
            { label: Image, name: image, widget: image },
            { label: Header, name: header, widget: string },
            { label: Description, name: description, widget: text },
          ]
      - file: "src/pages/landing/section2.md"
        label: "Section 2"
        name: "section2"
        fields:
          [
            { label: Image, name: image, widget: image },
            { label: Header, name: header, widget: string },
            { label: Description, name: description, widget: text },
          ]
      - file: "src/pages/landing/section3.md"
        label: "Section 3"
        name: "section3"
        fields:
          [
            { label: Image, name: image, widget: image },
            { label: Header, name: header, widget: string },
            { label: Description, name: description, widget: text },
          ]

  - name: "socialmedia"
    file: "src/pages/socialmedia/platforms.md"
    label: "Social Media"
    files:
      - file: "src/pages/socialmedia/platforms.md"
        label: "Platforms"
        name: "platforms"
        fields:
          - {
              label: Platform 1,
              name: platform1,
              widget: object,
              fields:
                [
                  { label: Logo, name: logo, widget: image },
                  { label: Website Link, name: website-link, widget: string },
                ],
            }
          - {
              label: Platform 2,
              name: platform2,
              widget: object,
              fields:
                [
                  { label: Logo, name: logo, widget: image },
                  { label: Website Link, name: website-link, widget: string },
                ],
            }
